@startuml
	'skin rose
	title Relationships - Class Diagram
	annotation "CRTP duck type"
	{
		+ {abstract} set()
		+ {abstract} operator[]()
		+ {abstract} data()
		+ {abstract} sequence()
		+ {abstract} iterator functions()
	}
	note right of "CRTP duck type"
		Conceptual interface, not real :
		Could be made into a c++ concept
	end note
	abstract vector_base <Writable, T, Count, Derived>
	{
		+ CRTP set()
		+ CRTP operator[]()
		+ CRTP data()
		+ CRTP sequence()
		+ CRTP iterator functions()
		+ length()
		+ size()
		+ as_derived()
		+ apply()
		+ shift()
		+ cshift()
		+ min()
		+ max()
		+ sum()
	}
	struct basic_vector<T, Size>
	{
		+ union
		+ {static} offsets
		+ set()
		+ operator[]()
		+ operator=()
		+ data()
		+ sequence()
		+ iterator functions()
		+ swap()
	}
	annotation basic_vector::anonymous_union
	{
		+ base
		+ swizzles
	}
	struct storage_wrapper<T, Size>
	{
		+ store
		+ {static} offsets
		+ set()
		+ operator[]()
		+ operator=()
		+ data()
		+ sequence()
		+ iterator functions()
		+ length()
		+ size()
		+ swap()
	}
	struct indexed_vector<T, Size, Count, ...Is>
	{
		+ base
		+ {static} offsets
		+ set()
		+ operator[]()
		+ operator=()
		+ data()
		+ sequence()
		+ iterator functions()
	}
	struct basic_matrix<T, Cols, Rows>
	{
		+ columns
		+ row()
		+ operator[]()
		+ operator=()
		+ data()
		+ iterator functions()
		+ length()
		+ column_length()
		+ size()
		+ column_size()
		+ swap()
	}
	class std::array<T, Size>
	{
	}
	vector_base <|-down- basic_vector: CRTP inherits
	vector_base <|-down- indexed_vector : CRTP inherits
	"CRTP duck type" ^.. basic_vector : duck implements
	"CRTP duck type" ^.. indexed_vector : duck implements
	basic_vector::anonymous_union::base "1" *-- "1" storage_wrapper : base
	basic_vector::anonymous_union::swizzles "1" *-- "many" indexed_vector : swizzles
	basic_vector::union "1" *-- "1" basic_vector::anonymous_union : nested anonymous union
	"CRTP duck type" <.. vector_base : Derived CRTP
	storage_wrapper::offsets "1" *-- "1" std::array : <std::size_t, Size>
	storage_wrapper::store "1" *-- "1" std::array : <T, Size>
	basic_vector::offsets "1" *-- "1" std::array : <std::size_t, Size>
	indexed_vector::offsets "1" *-- "1" std::array : <std::size_t, Count>
	indexed_vector::base "1" *-- "1" std::array : <T, Size>
	basic_matrix::columns "1" *.. "Cols" basic_vector : <T, Rows>
	basic_matrix::columns "1" *-- "1" std::array : <basic_vector<T, Rows>, Cols>
@enduml
